# Generated by Django 5.2.17 on 2026-08-15 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tendered_denominations', to='billing.bill')),
                ('denomination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_tenders', to='billing.denomination')),
            ],
            options={
                'ordering': ['-denomination__value'],
                'constraints': [models.UniqueConstraint(fields=('bill', 'denomination'), name='unique_tender_denomination_per_bill'), models.CheckConstraint(condition=models.Q(('count__gt', 0)), name='bill_tender_count_positive')],
            },
        ),
    ]
